image:
  repository: ovidiufeodorov/httpd
  tag: latest

#
# a range action will iterate over these and expose them as environment variables
#
colors:
  - blue
  - red
  - green
  - yellow

shapes:
  FIRST_SHAPE: square
  SECOND_SHAPE: circle
  THIRD_SHAPE: triangle

volumesAndMounts:
  volumes:
    - name: mount-0
      hostPath:
        path: /tmp
    - name: mount-1
      hostPath:
        path: /tmp
  volumesMounts:
    - mountPath: /a
      name: mount-0
    - mountPath: /b
      name: mount-1

