apiVersion: v1
kind: Pod
metadata:
  name: b-loop
  labels:
    color: '{{ .Values.color }}'
    shape: '{{ .Values.shape }}'
spec:
  containers:
    - name: loop
      image: docker.io/ovidiufeodorov/loop:latest
