apiVersion: v1
kind: Pod
metadata:
  name: 'httpd-pod'
  labels:
    function: 'httpd'
spec:
  containers:
  - name: 'httpd-container'
    image: httpd:2.4
---
apiVersion: v1
kind: Service
metadata:
  name: 'httpd-service'
spec:
  type: 'LoadBalancer'
  selector:
    function: 'httpd'
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 80