apiVersion: v1
kind: Pod
metadata:
  name: c-loop
  labels:
    color: '{{ .Values.color }}'
    common-color: '{{ .Values.commonColor }}'
spec:
  containers:
    - name: loop
      image: docker.io/ovidiufeodorov/loop:latest
