
spring.cloud.stream:
  bindings:
    channel-from-kinesis:
      destination: ovidiu-test

cloud:
  aws:
    region:
      static: us-west-2

logging:
  level:
    com:
      amazonaws: INFO
    org:
      apache:
        http: INFO