apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpd
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      env:
      {{- range list "blue" "red" "green" }}
      - name: {{ . | upper | printf "COLOR_%s" }}
        value: {{ . -}}
      {{ end }}
