apiVersion: v1
kind: Pod
metadata:
  name: httpd-2
spec:
  containers:
    - name: httpd
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      env:
      {{- range .Values.colors }}
      - name: {{ . | upper | printf "COLOR_%s" }}
        value: {{ . -}}
      {{ end }}
