apiVersion: v1
kind: Template
metadata:
  name: service-dependency
parameters:
  - name: PUBLIC_WILDCARD_DOMAIN
    required: true
objects:
- apiVersion: v1
  kind: ImageStreamImport
  metadata:
    name: rest-service
  spec:
    import: true
    images:
    - from:
        kind: DockerImage
        name: docker.io/novaordis/rest-service:latest
      to:
        name: latest
      importPolicy:
      referencePolicy:
        type:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: service-dependency
      instance: B
    name: b
  spec:
    replicas: 1
    selector:
      app: service-dependency
      instance: B
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: service-dependency
          instance: B
      spec:
        containers:
        - name: rest-service
          image: docker.io/novaordis/rest-service:latest
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rest-service
        from:
          kind: ImageStreamTag
          name: rest-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: b
    labels:
      app: service-dependency
      instance: B
  spec:
    ports:
    - name: tomcat-http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: service-dependency
      instance: B
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: b
  spec:
    host: b.${PUBLIC_WILDCARD_DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: b
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: service-dependency
      instance: A
    name: a
  spec:
    replicas: 1
    selector:
      app: service-dependency
      instance: A
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: service-dependency
          instance: A
      spec:
        containers:
        - name: rest-service
          image: docker.io/novaordis/rest-service:latest
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
          - name: REST_SERVICE_START
            value: "true"
        #
        # put service A deployment on hold until service B is available
        #
        initContainers:
        - name: b-dependency-checker
          image: rhel
          command: ['sh', '-c', 'while true; do response=$(curl -q http://${B_SERVICE_HOST}:${B_SERVICE_PORT_TOMCAT_HTTP}/rest-service/ping); [[ ${response} = "pong" ]] && break || { echo "waiting on B to start ..."; sleep 1; } done']
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rest-service
        from:
          kind: ImageStreamTag
          name: rest-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: a
    labels:
      app: service-dependency
      instance: A
  spec:
    ports:
    - name: tomcat-http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: service-dependency
      instance: A
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: a
  spec:
    host: a.${PUBLIC_WILDCARD_DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: a
    wildcardPolicy: None
